version: '3'

services:
  web:
    image: python:3.9
    command: gunicorn -b 0.0.0.0:5000 app:app
    volumes:
      - .:/usr/src/app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py
      FLASK_RUN_HOST: 0.0.0.0

