# docker-compose.yml

version: '3'
services:
  load_balancer:
    build: .
    container_name: load_balancer
    ports:
      - "5000:5000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
