 version:'3'
 services:

  load-balancer:
    image:load-balancer-image
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true


 server:
   image:server-image
