version: "3.9"
services:
  load-balancer:
    build: .
    image: loadbalancer
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    networks:
      - net1

networks:
  net1:
    driver: bridge
