# docker-compose.yml
version: '3'

services:
  load_balancer:
    build: .
    ports:
      - "5000:5000"
    privileged: true
    depends_on:
      - server1
      - server2
      - server3
    networks:
      - my_network

  server1:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=1
    networks:
      - my_network

  server2:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=2
    networks:
      - my_network

  server3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=3
    networks:
      - my_network

networks:
  my_network:
    driver: bridge